---
- name: Install PostgreSQL server & client
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true

- name: Ensure PostgreSQL is running
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: true

- name: Create Zabbix DB user (if not exists)
  ansible.builtin.shell: |
    sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='{{ zbx_db_user }}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER {{ zbx_db_user }} WITH PASSWORD '{{ zbx_db_password }}';"
  args:
    executable: /bin/bash

- name: Create Zabbix database (if not exists)
  ansible.builtin.shell: |
    sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw {{ zbx_db_name }} || \
    sudo -u postgres createdb -O {{ zbx_db_user }} {{ zbx_db_name }}
  args:
    executable: /bin/bash
