---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted


- name: restart php-fpm
  ansible.builtin.service:
    name: "php-fpm"
    state: restarted
  when: ansible_facts['distribution_release'] == 'noble' # 24.04 service is php-fpm


- name: restart php8.1-fpm
  ansible.builtin.service:
    name: php8.1-fpm
    state: restarted
  when: ansible_facts['distribution_release'] == 'jammy' # 22.04 default


- name: restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted


- name: restart zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted


- name: restart grafana-server
  ansible.builtin.service:
    name: grafana-server
    state: restarted