# Sensible defaults; override in group_vars/zabbix.yml
zabbix_version: "7.0"
php_timezone: "UTC"
zabbix_server_name: "zabbix.local"
zabbix_listen_port: 80
zbx_db_name: zabbix
zbx_db_user: zabbix
zbx_db_password: "Z4bb1x_Strong_Pass!"
grafana_admin_user: admin
grafana_admin_password: "Admin123!"
grafana_url: "http://localhost:3000"
zabbix_api_url: "http://localhost/zabbix/api_jsonrpc.php"
zabbix_grafana_plugin_id: "alexanderzobnin-zabbix-datasource"
zabbix_default_user: "Admin"
zabbix_default_password: "zabbix"